sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mastercheap/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mastercheap/react-test npm test

after_success:
  - docker build -t mastercheap/multi-client ./client
  - docker build -t mastercheap/multi-nginx ./nginx
  - docker build -t mastercheap/multi-server ./server
  - docker build -t mastercheap/multi-worker ./worker
  # Log in to the docker CLI
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker
  - docker push mastercheap/multi-client
  - docker push mastercheap/multi-nginx
  - docker push mastercheap/multi-server
  - docker push mastercheap/multi-worker
